micronaut:
  application:
    name: replayMicronaut
  server:
    port: 8087

jpa:
  default:
    packages-to-scan:
      - 'br.com.amz'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
r2dbc:
  datasources:
    default:
      schema-generate: CREATE
      dialect: MYSQL
      url: r2dbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3311}/${MYSQL_NAME:replay}
      username: r_user
      password: r_pwd
  migrate:
    dialect: mysql
    resources-paths:
      - classpath:/*.sql
flyway:
  datasources:
    default:
      enabled: true
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3311}/${MYSQL_NAME:replay}
      username: r_user
      password: r_pwd
      locations: classpath:/*.sql
      baseline-on-migrate: true
