name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '11'
          distribution: 'zulu'
      # Runs a single command using the runners shell
      
      - name: Build application
        run: ./gradlew clean build
      
      - name: Validate migrations
        run: ./gradlew flywayValidate
      
      - name: Run unit tests
        run: ./gradlew test
